language: elixir
elixir: 1.0.4
otp_release:
  - 17.1
sudo: false
before_script:
  - mix deps.get --only test
script:
  - mix test
after_script:
  - cd $TRAVIS_BUILD_DIR
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
